name: 'Pipeline'
on:
  pull_request:
  push:
    branches:
      - development
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed-packages:
    name: Determine which apps changed
    uses: ./.github/workflows/changed-packages.yaml

  lint-ui:
    runs-on: ubuntu-latest
    # TODO disabled for testing
    #needs: [changed-packages]
    #if: needs.changed-packages.outputs.ui_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint --filter frontend

  lint-api:
    runs-on: ubuntu-latest
    # TODO disabled for testing
    #needs: [changed-packages]
    #if: needs.changed-packages.outputs.api_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - run: pnpm run lint --filter backend

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - run: pnpm run build
